name: repo_viewer_reso
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  flutter_secure_storage: ^4.2.0
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  flutter_hooks: ^0.16.0
  hooks_riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/hooks_riverpod
  freezed_annotation: ^0.14.2
  webview_flutter: ^2.0.8
  flash: ^2.0.0
  auto_route: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  freezed: ^0.14.2
  auto_route_generator: ^2.1.0
  lint: ^1.5.3

dependency_overrides:
  flutter_riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/flutter_riverpod
  riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/riverpod

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
